import { Component } from '@angular/core';

function log(className: any) {
  console.log(className);
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'intro2angular';

  constructor() {
    console.log("This statement was generated by the constructor", this.aSimpleMethod(5, 7));
  }

  aSimpleMethod(a: number, b: number) {
    return a*b;
  }
}
